server:
  port: 8082 #服务端口
#myspcloud:
#  item:
#    url: http://127.0.0.1:8081/item/
###起个名字作为服务名称(该服务注册到eureka注册中心的名称，比如订单服务)
spring:
  application:
    name: app-order
###修改负载均衡策略
app-item:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#开启hystrix断路器
feign:
  hystrix:
    enabled: true
###服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@127.0.0.1:8100/eureka,http://root:123456@127.0.0.1:9100/eureka,http://root:123456@127.0.0.1:7100/eureka
    ###因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
    ###是否需要从eureka上检索服务
    fetch-registry: true
swagger:
  base-package: com.huang.order.controller