server:
  port: 8087
spring:
  application:
    name: app-gateway #指定服务名称
###服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@127.0.0.1:8100/eureka/,http://root:123456@127.0.0.1:9100/eureka/,http://root:123456@127.0.0.1:7100/eureka/
    ###因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
    ###是否需要从eureka上检索服务
    fetch-registry: true
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}###${server.port} #指定实例id
#zuul:
#  routes: #定义服务转发规则
#    item-service: #item-service这个名字任意取的
#      path: /item-service/** #配置请求URL的请求规则
#      serviceid: app-item
#    order-service:
#      path: /order-service/**
#      serviceid: app-order
      #url: http://127.0.0.1:8081 #真正的微服务地址，path匹配的请求都转发到这里
#开启所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"